version: 0.0
os: linux
files:
  - source: server.js
    destination: /home/ec2-user/app
  - source: package.json
    destination: /home/ec2-user/app
  - source: package-lock.json
    destination: /home/ec2-user/app
permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
