version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "Building application"
  post_build:
    commands:
      - zip -r app.zip .
artifacts:
  files:
    - '**/*'
